# Generated by Django 4.2.3 on 2023-07-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
